// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.DbContexts;

namespace WebAPI.Migrations
{
    [DbContext(typeof(BandAlbumContext))]
    [Migration("20201226184608_InitialMigrate")]
    partial class InitialMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Entities.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BandID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("AlbumID");

                    b.HasIndex("BandID");

                    b.ToTable("Album");

                    b.HasData(
                        new
                        {
                            AlbumID = 1,
                            BandID = 1,
                            Description = "Description of Album 1",
                            Title = "Album1"
                        },
                        new
                        {
                            AlbumID = 2,
                            BandID = 1,
                            Description = "Description of Album 2",
                            Title = "Album2"
                        },
                        new
                        {
                            AlbumID = 3,
                            BandID = 2,
                            Description = "Description of Album 3",
                            Title = "Album3"
                        },
                        new
                        {
                            AlbumID = 4,
                            BandID = 2,
                            Description = "Description of Album 4",
                            Title = "Album4"
                        });
                });

            modelBuilder.Entity("WebAPI.Entities.Band", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Founded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Band");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Founded = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Genre1",
                            Name = "FirstBand"
                        },
                        new
                        {
                            ID = 2,
                            Founded = new DateTime(2001, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Genre2",
                            Name = "SecondBand"
                        });
                });

            modelBuilder.Entity("WebAPI.Entities.Album", b =>
                {
                    b.HasOne("WebAPI.Entities.Band", "Band")
                        .WithMany()
                        .HasForeignKey("BandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
